name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: clean pychache files
      run: make clean

    - name: install libraries
      run: make install

    - name: Run test case
      run: make test
